name: Auto Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write   # to create releases
  actions: read

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract tag
        id: vars
        run: |
          TAG_REF="${GITHUB_REF##*/}"
          echo "tag=$TAG_REF" >> $GITHUB_OUTPUT
          # Derive previous tag for changelog (if any)
          PREV_TAG=$(git describe --tags --abbrev=0 "$TAG_REF^" 2>/dev/null || echo "")
          echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT

      - name: Generate release notes
        id: notes
        run: |
          tag='${{ steps.vars.outputs.tag }}'
          prev='${{ steps.vars.outputs.prev_tag }}'
          {
            echo "## Release $tag";
            echo;
            if [ -n "$prev" ]; then
              echo "### Changes since $prev";
              echo;
              git log --pretty=format:'- %h %s (%an)' "$prev..$tag";
              echo;
            else
              echo "Initial generated release notes (no previous tag detected).";
              echo;
              git log --pretty=format:'- %h %s (%an)' "$tag" -n 100;
            fi
            echo;
            echo "_Automated release generated by workflow_.";
          } > RELEASE_NOTES.md
          echo "file=RELEASE_NOTES.md" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          name: ${{ steps.vars.outputs.tag }}
          body_path: ${{ steps.notes.outputs.file }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show release URL
        run: echo "Release created for tag ${{ steps.vars.outputs.tag }}"
