name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -race -coverprofile=coverage.out ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=5m
